### PR TITLE
Fixing the drupal8 appliance.

### PR DESCRIPTION
**Pull request by dashohoxha**
It is not finished yet, but making a PR allows us to comment and discuss the commits.

### CODE REVIEW

**Comment by JedMeister** [comment]
Great thanks @dashohoxha 

I need to tag all the repos for the v14.0 release so won't merge this immediately. 

Also this will close https://github.com/turnkeylinux/tracker/issues/451

**Comment by JedMeister** [comment]
Closing this PR in favour of #5 (that one includes all these commits and some more...)

Thanks for your help with this one @dashohoxha :+1:

**Comment by dashohoxha** [comment]
Sorry for not being able to finish everything.

**Comment by JedMeister** [comment]
Thanks for the help you did give. :smile:

**Pull request closed without merging**
